// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Complete log information about a single HTTP request to an App Engine
/// application.
public struct RequestLog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Application that handled this request.
  public var appId: Swift.String = Swift.String()

  /// Module of the application that handled this request.
  public var moduleId: Swift.String = Swift.String()

  /// Version of the application that handled this request.
  public var versionId: Swift.String = Swift.String()

  /// Globally unique identifier for a request, which is based on the request
  /// start time.  Request IDs for requests which started later will compare
  /// greater as strings than those for requests which started earlier.
  public var requestId: Swift.String = Swift.String()

  /// Origin IP address.
  public var ip: Swift.String = Swift.String()

  /// Time when the request started.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Time when the request finished.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Latency of the request.
  public var latency: GoogleCloudWkt.Duration? = nil

  /// Number of CPU megacycles used to process request.
  public var megaCycles: Swift.Int64 = Swift.Int64()

  /// Request method. Example: `"GET"`, `"HEAD"`, `"PUT"`, `"POST"`, `"DELETE"`.
  public var method: Swift.String = Swift.String()

  /// Contains the path and query portion of the URL that was requested. For
  /// example, if the URL was "http://example.com/app?name=val", the resource
  /// would be "/app?name=val".  The fragment identifier, which is identified by
  /// the `#` character, is not included.
  public var resource: Swift.String = Swift.String()

  /// HTTP version of request. Example: `"HTTP/1.1"`.
  public var httpVersion: Swift.String = Swift.String()

  /// HTTP response status code. Example: 200, 404.
  public var status: Swift.Int32 = Swift.Int32()

  /// Size in bytes sent back to client by request.
  public var responseSize: Swift.Int64 = Swift.Int64()

  /// Referrer URL of request.
  public var referrer: Swift.String = Swift.String()

  /// User agent that made the request.
  public var userAgent: Swift.String = Swift.String()

  /// The logged-in user who made the request.
  ///
  /// Most likely, this is the part of the user's email before the `@` sign.  The
  /// field value is the same for different requests from the same user, but
  /// different users can have similar names.  This information is also
  /// available to the application via the App Engine Users API.
  ///
  /// This field will be populated starting with App Engine 1.9.21.
  public var nickname: Swift.String = Swift.String()

  /// File or class that handled the request.
  public var urlMapEntry: Swift.String = Swift.String()

  /// Internet host and port number of the resource being requested.
  public var host: Swift.String = Swift.String()

  /// An indication of the relative cost of serving this request.
  public var cost: Swift.Double = Swift.Double()

  /// Queue name of the request, in the case of an offline request.
  public var taskQueueName: Swift.String = Swift.String()

  /// Task name of the request, in the case of an offline request.
  public var taskName: Swift.String = Swift.String()

  /// Whether this was a loading request for the instance.
  public var wasLoadingRequest: Swift.Bool = Swift.Bool()

  /// Time this request spent in the pending request queue.
  public var pendingTime: GoogleCloudWkt.Duration? = nil

  /// If the instance processing this request belongs to a manually scaled
  /// module, then this is the 0-based index of the instance. Otherwise, this
  /// value is -1.
  public var instanceIndex: Swift.Int32 = Swift.Int32()

  /// Whether this request is finished or active.
  public var finished: Swift.Bool = Swift.Bool()

  /// Whether this is the first `RequestLog` entry for this request.  If an
  /// active request has several `RequestLog` entries written to Stackdriver
  /// Logging, then this field will be set for one of them.
  public var first: Swift.Bool = Swift.Bool()

  /// An identifier for the instance that handled the request.
  public var instanceId: Swift.String = Swift.String()

  /// A list of log lines emitted by the application while serving this request.
  public var line: [LogLine] = []

  /// App Engine release version.
  public var appEngineRelease: Swift.String = Swift.String()

  /// Stackdriver Trace identifier for this request.
  public var traceId: Swift.String = Swift.String()

  /// If true, the value in the 'trace_id' field was sampled for storage in a
  /// trace backend.
  public var traceSampled: Swift.Bool = Swift.Bool()

  /// Source code for the application that handled this request. There can be
  /// more than one source reference per deployed application if source code is
  /// distributed among multiple repositories.
  public var sourceReference: [SourceReference] = []

  /// Initialize a new instance of `RequestLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RequestLog().with { $0.appId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.logging.v1.RequestLog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
