// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Complete log information about a single HTTP request to an App Engine
/// application.
public struct RequestLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Application that handled this request.
  public var appId: Swift.String = Swift.String()

  /// Module of the application that handled this request.
  public var moduleId: Swift.String = Swift.String()

  /// Version of the application that handled this request.
  public var versionId: Swift.String = Swift.String()

  /// Globally unique identifier for a request, which is based on the request
  /// start time.  Request IDs for requests which started later will compare
  /// greater as strings than those for requests which started earlier.
  public var requestId: Swift.String = Swift.String()

  /// Origin IP address.
  public var ip: Swift.String = Swift.String()

  /// Time when the request started.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// Time when the request finished.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Latency of the request.
  public var latency: GoogleWKT.Duration? = nil

  /// Number of CPU megacycles used to process request.
  public var megaCycles: Swift.Int64 = Swift.Int64()

  /// Request method. Example: `"GET"`, `"HEAD"`, `"PUT"`, `"POST"`, `"DELETE"`.
  public var method: Swift.String = Swift.String()

  /// Contains the path and query portion of the URL that was requested. For
  /// example, if the URL was "http://example.com/app?name=val", the resource
  /// would be "/app?name=val".  The fragment identifier, which is identified by
  /// the `#` character, is not included.
  public var resource: Swift.String = Swift.String()

  /// HTTP version of request. Example: `"HTTP/1.1"`.
  public var httpVersion: Swift.String = Swift.String()

  /// HTTP response status code. Example: 200, 404.
  public var status: Swift.Int32 = Swift.Int32()

  /// Size in bytes sent back to client by request.
  public var responseSize: Swift.Int64 = Swift.Int64()

  /// Referrer URL of request.
  public var referrer: Swift.String = Swift.String()

  /// User agent that made the request.
  public var userAgent: Swift.String = Swift.String()

  /// The logged-in user who made the request.
  ///
  /// Most likely, this is the part of the user's email before the `@` sign.  The
  /// field value is the same for different requests from the same user, but
  /// different users can have similar names.  This information is also
  /// available to the application via the App Engine Users API.
  ///
  /// This field will be populated starting with App Engine 1.9.21.
  public var nickname: Swift.String = Swift.String()

  /// File or class that handled the request.
  public var urlMapEntry: Swift.String = Swift.String()

  /// Internet host and port number of the resource being requested.
  public var host: Swift.String = Swift.String()

  /// An indication of the relative cost of serving this request.
  public var cost: Swift.Double = Swift.Double()

  /// Queue name of the request, in the case of an offline request.
  public var taskQueueName: Swift.String = Swift.String()

  /// Task name of the request, in the case of an offline request.
  public var taskName: Swift.String = Swift.String()

  /// Whether this was a loading request for the instance.
  public var wasLoadingRequest: Swift.Bool = Swift.Bool()

  /// Time this request spent in the pending request queue.
  public var pendingTime: GoogleWKT.Duration? = nil

  /// If the instance processing this request belongs to a manually scaled
  /// module, then this is the 0-based index of the instance. Otherwise, this
  /// value is -1.
  public var instanceIndex: Swift.Int32 = Swift.Int32()

  /// Whether this request is finished or active.
  public var finished: Swift.Bool = Swift.Bool()

  /// Whether this is the first `RequestLog` entry for this request.  If an
  /// active request has several `RequestLog` entries written to Stackdriver
  /// Logging, then this field will be set for one of them.
  public var first: Swift.Bool = Swift.Bool()

  /// An identifier for the instance that handled the request.
  public var instanceId: Swift.String = Swift.String()

  /// A list of log lines emitted by the application while serving this request.
  public var line: [LogLine] = []

  /// App Engine release version.
  public var appEngineRelease: Swift.String = Swift.String()

  /// Stackdriver Trace identifier for this request.
  public var traceId: Swift.String = Swift.String()

  /// If true, the value in the 'trace_id' field was sampled for storage in a
  /// trace backend.
  public var traceSampled: Swift.Bool = Swift.Bool()

  /// Source code for the application that handled this request. There can be
  /// more than one source reference per deployed application if source code is
  /// distributed among multiple repositories.
  public var sourceReference: [SourceReference] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RequestLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RequestLog().with { $0.appId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let appId = CodingKeys(stringValue: "appId")
    static let moduleId = CodingKeys(stringValue: "moduleId")
    static let versionId = CodingKeys(stringValue: "versionId")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let ip = CodingKeys(stringValue: "ip")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let latency = CodingKeys(stringValue: "latency")
    static let megaCycles = CodingKeys(stringValue: "megaCycles")
    static let method = CodingKeys(stringValue: "method")
    static let resource = CodingKeys(stringValue: "resource")
    static let httpVersion = CodingKeys(stringValue: "httpVersion")
    static let status = CodingKeys(stringValue: "status")
    static let responseSize = CodingKeys(stringValue: "responseSize")
    static let referrer = CodingKeys(stringValue: "referrer")
    static let userAgent = CodingKeys(stringValue: "userAgent")
    static let nickname = CodingKeys(stringValue: "nickname")
    static let urlMapEntry = CodingKeys(stringValue: "urlMapEntry")
    static let host = CodingKeys(stringValue: "host")
    static let cost = CodingKeys(stringValue: "cost")
    static let taskQueueName = CodingKeys(stringValue: "taskQueueName")
    static let taskName = CodingKeys(stringValue: "taskName")
    static let wasLoadingRequest = CodingKeys(stringValue: "wasLoadingRequest")
    static let pendingTime = CodingKeys(stringValue: "pendingTime")
    static let instanceIndex = CodingKeys(stringValue: "instanceIndex")
    static let finished = CodingKeys(stringValue: "finished")
    static let first = CodingKeys(stringValue: "first")
    static let instanceId = CodingKeys(stringValue: "instanceId")
    static let line = CodingKeys(stringValue: "line")
    static let appEngineRelease = CodingKeys(stringValue: "appEngineRelease")
    static let traceId = CodingKeys(stringValue: "traceId")
    static let traceSampled = CodingKeys(stringValue: "traceSampled")
    static let sourceReference = CodingKeys(stringValue: "sourceReference")

    static let _knownKeys: Set<Swift.String> = [
      "appId",
      "moduleId",
      "versionId",
      "requestId",
      "ip",
      "startTime",
      "endTime",
      "latency",
      "megaCycles",
      "method",
      "resource",
      "httpVersion",
      "status",
      "responseSize",
      "referrer",
      "userAgent",
      "nickname",
      "urlMapEntry",
      "host",
      "cost",
      "taskQueueName",
      "taskName",
      "wasLoadingRequest",
      "pendingTime",
      "instanceIndex",
      "finished",
      "first",
      "instanceId",
      "line",
      "appEngineRelease",
      "traceId",
      "traceSampled",
      "sourceReference",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appId) {
      self.appId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .moduleId) {
      self.moduleId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .versionId) {
      self.versionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ip) {
      self.ip = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    self.latency = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .latency)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .megaCycles) {
      self.megaCycles = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .method) {
      self.method = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
      self.resource = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .httpVersion) {
      self.httpVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .status) {
      self.status = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .responseSize) {
      self.responseSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .referrer) {
      self.referrer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userAgent) {
      self.userAgent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nickname) {
      self.nickname = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .urlMapEntry) {
      self.urlMapEntry = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .host) {
      self.host = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .cost) {
      self.cost = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .taskQueueName) {
      self.taskQueueName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .taskName) {
      self.taskName = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .wasLoadingRequest) {
      self.wasLoadingRequest = value
    }
    self.pendingTime = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .pendingTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .instanceIndex) {
      self.instanceIndex = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .finished) {
      self.finished = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .first) {
      self.first = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceId) {
      self.instanceId = value
    }
    if let value = try container.decodeIfPresent([LogLine].self, forKey: .line) {
      self.line = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appEngineRelease) {
      self.appEngineRelease = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .traceId) {
      self.traceId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .traceSampled) {
      self.traceSampled = value
    }
    if let value = try container.decodeIfPresent([SourceReference].self, forKey: .sourceReference) {
      self.sourceReference = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.appId, forKey: .appId)
    try container.encode(self.moduleId, forKey: .moduleId)
    try container.encode(self.versionId, forKey: .versionId)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.ip, forKey: .ip)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encodeIfPresent(self.latency, forKey: .latency)
    try container.encode(self.megaCycles, forKey: .megaCycles)
    try container.encode(self.method, forKey: .method)
    try container.encode(self.resource, forKey: .resource)
    try container.encode(self.httpVersion, forKey: .httpVersion)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.responseSize, forKey: .responseSize)
    try container.encode(self.referrer, forKey: .referrer)
    try container.encode(self.userAgent, forKey: .userAgent)
    try container.encode(self.nickname, forKey: .nickname)
    try container.encode(self.urlMapEntry, forKey: .urlMapEntry)
    try container.encode(self.host, forKey: .host)
    try container.encode(self.cost, forKey: .cost)
    try container.encode(self.taskQueueName, forKey: .taskQueueName)
    try container.encode(self.taskName, forKey: .taskName)
    try container.encode(self.wasLoadingRequest, forKey: .wasLoadingRequest)
    try container.encodeIfPresent(self.pendingTime, forKey: .pendingTime)
    try container.encode(self.instanceIndex, forKey: .instanceIndex)
    try container.encode(self.finished, forKey: .finished)
    try container.encode(self.first, forKey: .first)
    try container.encode(self.instanceId, forKey: .instanceId)
    try container.encode(self.line, forKey: .line)
    try container.encode(self.appEngineRelease, forKey: .appEngineRelease)
    try container.encode(self.traceId, forKey: .traceId)
    try container.encode(self.traceSampled, forKey: .traceSampled)
    try container.encode(self.sourceReference, forKey: .sourceReference)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.logging.v1.RequestLog"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
